# Generated by Django 4.2.1 on 2023-09-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
