# Generated by Django 4.2.1 on 2023-09-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_classes_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='participants',
        ),
    ]
