# Generated by Django 4.2.1 on 2023-09-11 12:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_lessons_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['start_time', 'pk']},
        ),
        migrations.AddField(
            model_name='classes',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
