# Generated by Django 4.2.1 on 2023-09-15 14:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_classes_options_classes_email_classes_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
